MvcStokProject/MvcStokProject/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStokProject.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace MvcStokProject.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun
        MvcDbStokEntities1 db = new MvcDbStokEntities1();
        public ActionResult Index()
        {
            //var degerler = db.TBLURUNLER.ToList();
            var degerler = db.TBLURUNLER.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult UrunEkle()
        {
            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            return View();
        }

        [HttpPost]//komut verince çalışır
        public ActionResult UrunEkle(TBLURUNLER p1)
        {
            var ktg = db.TBLKATEGORILER.Where(m => m.KATEGORIID == p1.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            p1.TBLKATEGORILER = ktg;
            db.TBLURUNLER.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        {
            var urun = db.TBLURUNLER.Find(id);
            db.TBLURUNLER.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UrunGetir(int id)
        {
            var urngtr = db.TBLURUNLER.Find(id);
            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            return View("UrunGetir", urngtr);
        }
        public ActionResult Guncelle(TBLURUNLER p1)
        {
           var urnguncelle=db.TBLURUNLER.Find(p1.URUNID);
            urnguncelle.URUNAD = p1.URUNAD;
            urnguncelle.MARKA= p1.MARKA;
            //urnguncelle.URUNKATEGORI = p1.URUNKATEGORI;
            var ktg = db.TBLKATEGORILER.Where(m => m.KATEGORIID == p1.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            urnguncelle.URUNKATEGORI = ktg.KATEGORIID;
            urnguncelle.FİYAT = p1.FİYAT;
            urnguncelle.STOK=p1.STOK;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

MvcStokProject/MvcStokProject/Views/Urun/Index.cshtml
@using MvcStokProject.Models.Entity


@model List<TBLURUNLER>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>
            <th>ÜRÜN ID</th>
            <th>ÜRÜN ADI</th>
            <th>MARKASI</th>
            <th>KATEGORİ ADI</th>
            <th>FİYAT</th>
            <th>STOK</th>
            <th>SİL</th>
            <th>GÜNCELLE</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var urn in Model)
        {
            <tr>
                <th>@urn.URUNID</th>
                <td>@urn.URUNAD</td>
                <td>@urn.MARKA</td>
                <td>@urn.TBLKATEGORILER.KATEGORIAD</td>
                <td>@urn.FİYAT</td>
                <td>@urn.STOK</td>
                <td style="width:10px"><a href="/Urun/Sil/@urn.URUNID" class="btn btn-danger">SİL</a></td>
                <td style="width:10px"><a href="/Urun/UrunGetir/@urn.URUNID" class="btn btn-success">GÜNCELLE</a></td>
                
            </tr>


        }
    </tbody>
</table>

<br />
<a class="btn btn-primary" href="/Urun/UrunEkle">YENİ ÜRÜN EKLE</a>
<br />

<script type="text/javascript" src="https:////cdn.datatables.net/2.0.2/js/dataTables.min.js"></script>

<link href="~/Content/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />


<script>
    $('#tbl1').DataTable();
</script>

MvcStokProject/MvcStokProject/Views/Urun/UrunEkle.cshtml
@model MvcStokProject.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "UrunEkle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post" class="form-group">
    <div>
        <label>ÜRÜN AD</label>
        <input type="text" class="form-control" name="URUNAD" required="" />
    </div>

    <div>
        <label>MARKA</label>
        <input type="text" class="form-control" name="MARKA" required="" placeholder="Bu alana markayı yazın"/>
    </div>

    <div>
        <label>KATEGORİ SEÇİNİZ</label>
        @Html.DropDownListFor(m =>m.TBLKATEGORILER.KATEGORIID, (List<SelectListItem>)ViewBag.dgr, new {@class="form-control"})
       
        
    </div>

    <div>
        <label>FİYAT</label> 
        <input type="text" class="form-control" name="FİYAT" required=""/>
    </div>

    <div>
        <label>STOK ADET</label>
        <input type="text" class="form-control" name="STOK" required=""/>
    </div>

    <button class="btn btn-info" style="margin-top:15px">
        Ürün Ekle
    </button>
</form>

MvcStokProject/MvcStokProject/Views/Urun/UrunGetir.cshtml
@model MvcStokProject.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Urun", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.URUNID)
        @Html.TextBoxFor(m => m.URUNID, new { @class = "form-control" })

    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.URUNAD)
        @Html.TextBoxFor(m => m.URUNAD, new { @class = "form-control" })

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.MARKA)
        @Html.TextBoxFor(m => m.MARKA, new { @class = "form-control" })

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.URUNKATEGORI)
        @Html.DropDownListFor(m => m.TBLKATEGORILER.KATEGORIID, (List <SelectListItem>) ViewBag.dgr, new {@class="form-control"})
        @*@Html.TextBoxFor(m => m.TBLKATEGORILER.KATEGORIAD, new { @class = "form-control" })*@

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.FİYAT)
        @Html.TextBoxFor(m => m.FİYAT, new { @class = "form-control" })

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.STOK)
        @Html.TextBoxFor(m => m.STOK, new { @class = "form-control" })

    </div>
    <div>
        <button class="btn btn-warning">ÜRÜN TABLOSU GÜNCELLE</button>

    </div>
}