MvcStokProject/MvcStokProject/Controllers/MusterıController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStokProject.Models.Entity;

namespace MvcStokProject.Controllers
{
    public class MusterıController : Controller
    {
        // GET: Musterı
        MvcDbStokEntities1 db = new MvcDbStokEntities1();
        public ActionResult Index(string p)
        {
            //var degerler = db.TBLMUSTERILER.ToList();
            var degerler = from d in db.TBLMUSTERILER select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.MUSTERIAD.Contains(p));
            }
            return View(degerler.ToList());
        }

        [HttpGet]
        public ActionResult MusteriEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult MusteriEkle(TBLMUSTERILER p1)
        {
            if (!ModelState.IsValid)
            {
                return View("MusteriEkle");
            }
            db.TBLMUSTERILER.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Sil(int id)
        {
            var musteri = db.TBLMUSTERILER.Find(id);
            db.TBLMUSTERILER.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriGetir(int id)
        {
            var musteri = db.TBLMUSTERILER.Find(id);
            return View("MusteriGetir", musteri);
        }
        public ActionResult Guncelle(TBLMUSTERILER p1)
        {
            var musteri = db.TBLMUSTERILER.Find(p1.MUSTERIID);
            musteri.MUSTERIAD = p1.MUSTERIAD;
            musteri.MUSTERISOYADI = p1.MUSTERISOYADI;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }


}

MvcStokProject/MvcStokProject/Views/Musterı/Index.cshtml
@using MvcStokProject.Models.Entity
@model List<TBLMUSTERILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@using (Html.BeginForm("Index", "Musterı", FormMethod.Get))
{
    <p>
        <b>Aranıcak Müşteri Adı:</b>@Html.TextBox("p")
        <input type="submit" value="Ara" />
    </p>
    
}
<table class="table table-bordered">
    <tr>
        <th>MÜŞTERİ ID</th>
        <th>MÜŞTERİ ADI</th>
        <th>MÜŞTERİ SOYADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th>ALERT(SORU İLE SİLME İŞLEMİ)</th>

    </tr>

    <tbody>
        @foreach (var mstr in Model)
        {
            <tr>
                <th>@mstr.MUSTERIID</th>
                <td>@mstr.MUSTERIAD</td>
                <td>@mstr.MUSTERISOYADI</td>
                <td style="width:10px"><a href="/Musterı/Sil/@mstr.MUSTERIID" class="btn btn-danger">SİL</a></td>
                <td style="width:10px"><a href="/Musterı/MusteriGetir/@mstr.MUSTERIID" class="btn btn-success">GÜNCELLE</a></td>
                <td style="width:10px">@Html.ActionLink("Sil", "Sil", new { id = mstr.MUSTERIID }, new { @class = "btn btn-warning", onclick = "return confirm('GERÇEKTEN SİLMEK İSTİYOR MUSUN')" })</td>

            </tr>
        }
    </tbody>
</table>


<a href="/Musterı/MusteriEkle" class="btn btn-primary">YENİ MÜŞTERİ EKLE</a>

MvcStokProject/MvcStokProject/Views/Musterı/MusteriEkle.cshtml
@model MvcStokProject.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "MusteriEkle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">

    <div>
        <label>Müşteri Adı</label>

        @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })


        @Html.ValidationMessageFor(m => m.MUSTERIAD, "", new { @style = "color:red" })

    </div>

    <div>
        <label>Müşteri Soyadı</label>

        @Html.TextBoxFor(m => m.MUSTERISOYADI, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MUSTERISOYADI, "", new { @style = "color:red" })
    </div>


    <button class="btn btn-info" style="margin-top:15px" id="btn1">
        Müşteri Ekle

    </button>

    <script>

        $('#btn1').click(function () {
            alert("Yeni Müşteri Eklendi")



        })
    </script>




</form>

MvcStokProject/MvcStokProject/Views/Musterı/MusteriGetir.cshtml
@model MvcStokProject.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Musterı", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.MUSTERIID)
        @Html.TextBoxFor(m => m.MUSTERIID, new { @class = "form-control" })

    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.MUSTERIAD)
        @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })

    </div>

    <div class="form-group">
        @Html.LabelFor(m=>m.MUSTERISOYADI)
        @Html.TextBoxFor(m => m.MUSTERISOYADI, new { @class = "form-control" })

    </div>

    <div>

        <button class="btn btn-warning">MÜŞTERİ GÜNCELLE</button>
    </div>

}